[package]
name = "ares"
version = "0.1.0"
authors = ["Edward Amsden <edward@tlon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ares_macros = { path = "../ares_macros" }
bitvec = "1.0.0"
criterion = "0.4"
either = "1.6.1"
intmap = "1.1.0"
libc = "0.2.126"
memmap = "0.7.0"
murmur3 = { git = "https://github.com/tloncorp/murmur3", branch = "eamsden/non_copying" }
num-derive = "0.3"
num-traits = "0.2"

[[bin]]
name = "cue_pill"
path = "benches/cue_pill.rs"

[[bin]]
name = "ares"
path = "src/main.rs"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[features]
check_acyclic=[]
