[package]
name = "ares"
version = "0.1.0"
authors = ["Edward Amsden <edward@tlon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
ibig = { git = 'https://github.com/urbit/ibig-rs' }

[dependencies]
ares_macros = { path = "../ares_macros" }
bitvec = "1.0.0"
either = "1.6.1"
libc = "0.2.126"
murmur3 = { git = "https://github.com/tloncorp/murmur3", branch = "eamsden/non_copying" }
memmap = "0.7.0"
intmap = "1.1.0"
num-traits = "0.2"
num-derive = "0.3"
criterion = "0.4"
static_assertions = "1.1.0"
ibig = "0.3.6"
assert_no_alloc = "1.1.2"

[[bin]]
name = "cue_pill"
path = "benches/cue_pill.rs"

[[bin]]
name = "ares"
path = "src/main.rs"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[features]
check_acyclic=[]
