on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

defaults:
  run:
    working-directory: rust

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      # Install nix, required by nix-shell-action
      - uses: cachix/install-nix-action@v23
        name: Install Nix
        with:
          extra_nix_config: "extra-experimental-features = nix-command flakes"

      # Check formatting
      - name: Format
        run: |
          cd ares
          nix develop --command bash -c "cargo fmt --check"

      # See clippy linter docs: https://github.com/rust-lang/rust-clippy
      #
      # First linter is set to fail for all warnings, then ignored warnings are
      # explicitly listed
      #
      # XX TODO make a script with all the flags for the linter
      - name: Lint
        run: |
          cd ares
          nix develop --command bash -c "cargo clippy --all-targets --no-deps -- -D warnings -A clippy::missing_safety_doc"

      # Build Ares
      - name: Build
        run: |
          cd ares
          nix develop --command bash -c "cargo build --release --verbose --features check_all"

      # Run tests
      - name: Test
        run: |
          cd ares
          nix develop --command bash -c "cargo test --verbose -- --test-threads=1"

